### ISSUE TITLE
AWI bug in get_surface 

### ISSUE THREAD

**Issue by ajutila** [kingjml/pySnowRadar#24]
AWI data in its current state includes All-NaN traces and random traces where the last value has the highest value. That screws up the function `get_surface`, which in turn messes up `get_bounds`. Therefore the `radar_subset` has wrong boundaries, which allows radar data with NaN values to emerge, which in turn ends up ruining the interface picker.
```
    def get_surface(self, smooth=True):
        '''
        Simple surface tracker based on maximum
        This should be refined and is largely a place holder 
        TODO: surf_time is broken unless the time axis is interpolated
        
        '''
        surf_bin = np.nanargmax(self.data_radar, axis=0)
        surf_time = np.interp(surf_bin,np.arange(0,len(self.time_fast)),self.time_fast)
        return surf_bin , surf_time
```

So far my hack has been using the elevation compensation, assigning 0 values for NaNs `surf_bin = np.nanargmax(np.nan_to_num(self.data_radar), axis=0)`, and finding the approximate modal value of the surface bin and using a threshold around it for boundaries
```
from scipy import stats
surf_bin_mode = stats.mode(np.around(radar_dat.surf_bin,-2)).mode[0]
upper = surf_bin_mode - 1000
lower = surf_bin_mode + 500
radar_subset = radar_dat.data_radar[upper:lower, :]
```

**Comment by kingjml** [comment]
This emails an AWI issue with calibration flights. Will move to close as a general issue.
