### ISSUE TITLE
Understanding the new picker Wavelet_JK

### ISSUE THREAD

**Issue by ajutila** [kingjml/pySnowRadar#35]
Hi Josh and Mike!

I'm now trying to get up to speed here and thought to start by checking the code for the new wavelet picker. So, here comes a bunch of questions to make sure if I have understood correctly.

1) Wavelet_JK uses a first order Gaussian wavelet in contrast to the original Wavelet_TN (Haar) and the first iteration Josh came up with in the end of last summer (Ricker/Mexican hat), correct?

2) The Haar wavelet of Wavelet_TN works like a step function, therefore first radar returns (tops of dunes, ridges, etc.) pop up strongly and the resulting snow depth is close to the maximum snow depth rather than the mean. Whereas in the first order Gaussian wavelet the transition is more gradual, which is why the resulting snow depth is closer to truth.

3) Why is `lin_scale_vect` used to calculate `log_coefs` and not `log_scale_vect`?

https://github.com/kingjml/pySnowRadar/blob/63a86749d0c35fe311f8c57f5be0478991ed4fb2/pySnowRadar/algorithms/Wavelet.py#L86

4) To me it seems that Wavelet_JK takes an argument `cwt_precision` but does not use it at all. Is it because it uses the cwt function from the PyWavelets package?

Otherwise, it looks great, looking forward to have a crack at it!

**Comment by kingjml** [comment]
Moving to close are this picker has been replaced.
